global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'railway-prom'

scrape_configs:
  - job_name: bapp
    static_configs:
      - targets:
          - bapp.railway.internal:8081
    metrics_path: /metrics
